version: '3'
services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_DB: FlaskProject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - mynetwork

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_flask_app
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
